# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
